### ISSUE TITLE
make the INTERNAL_KEY_PREFIX configurable

### ISSUE THREAD

**Issue by WenyXu** [tikv/raft-engine#334]
We run into a problem. We are trying to use `raft-engine` as our Kv store. However, Our existing business logic uses the keys with the prefix `__`.  How about let's make the INTERNAL_KEY_PREFIX configurable?

**Comment by tabokie** [comment]
Haha, very sorry for the troubles. However I don't think it's a good idea to make the prefix changeable because we have no way to detect whether a changed binary is deployed on the old data.

To solve your particular problem, I think we can probably reduce the scope of internal keys to the one key being used (by atomic group). Are you interested in making this change?

**Comment by WenyXu** [comment]
Yep, Let me handle this
